# ----------------------------------------------------------------------------
# Build & Deploy `dropbox-ui` as GitHub Pages for /gpthani/
# ----------------------------------------------------------------------------
name: Deploy DropBox UI to GH Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build
        working-directory: dropbox-ui
        run: |
          npm ci
          npm run build

      - name: Copy to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -r dropbox-ui/dist/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: docs
